"""Insurer API keys and the driver-key salt. Both live in Postgres, generated by the server."""

import hashlib
import secrets
from datetime import UTC, datetime, timedelta

from sqlalchemy import select
from sqlalchemy.dialects.postgresql import insert
from sqlalchemy.orm import Session

from app.models import ApiKey, AppSetting

SALT_SETTING = "driver_api_key_salt"
KEY_TOKEN_PREFIX = "dsk_"
KEY_PREFIX_LEN = 8
LAST_USED_RESOLUTION = timedelta(minutes=1)
MAX_NAME_LEN = 80


def get_salt(db: Session) -> str:
    """Return the salt for hashing API keys, generating and storing it on first use."""
    row = db.get(AppSetting, SALT_SETTING)
    if row is None:
        # ON CONFLICT keeps this safe when two requests race to create the salt.
        db.execute(
            insert(AppSetting)
            .values(key=SALT_SETTING, value=secrets.token_urlsafe(32), created_at=_now())
            .on_conflict_do_nothing(index_elements=["key"])
        )
        db.commit()
        row = db.get(AppSetting, SALT_SETTING)
    assert row is not None
    return row.value


def hash_key(db: Session, api_key: str) -> str:
    return hashlib.sha256(f"{get_salt(db)}:{api_key}".encode()).hexdigest()


def generate_key() -> str:
    return secrets.token_urlsafe(32)


def create_api_key(db: Session, name: str, created_by_user_id: int | None) -> tuple[ApiKey, str]:
    """Create an insurer key. The plaintext is returned once and is not stored."""
    name = name.strip()
    if not name:
        raise ValueError("Name must not be empty.")
    if len(name) > MAX_NAME_LEN:
        raise ValueError(f"Name must be at most {MAX_NAME_LEN} characters.")
    plaintext = KEY_TOKEN_PREFIX + generate_key()
    record = ApiKey(
        name=name,
        key_prefix=plaintext[:KEY_PREFIX_LEN],
        key_hash=hash_key(db, plaintext),
        created_by_user_id=created_by_user_id,
    )
    db.add(record)
    db.commit()
    return record, plaintext


def find_active_key(db: Session, api_key: str) -> ApiKey | None:
    """Return the matching unrevoked key and record its use (at most once a minute)."""
    record = db.scalar(
        select(ApiKey).where(ApiKey.key_hash == hash_key(db, api_key), ApiKey.revoked_at.is_(None))
    )
    if record is None:
        return None
    now = _now()
    if record.last_used_at is None or now - record.last_used_at >= LAST_USED_RESOLUTION:
        record.last_used_at = now
        db.commit()
    return record


def revoke_api_key(db: Session, key_id: int) -> bool:
    """Revoke a key; False if it does not exist. Revoking twice keeps the first time."""
    record = db.get(ApiKey, key_id)
    if record is None:
        return False
    if record.revoked_at is None:
        record.revoked_at = _now()
        db.commit()
    return True


def _now() -> datetime:
    return datetime.now(UTC)
