// BT theme tokens (source: docs/design-system.md section 8). Hex only; light mode only.
export const theme = {
  colors: {
    cream: '#EDF0F6',
    ink: '#1A2230',
    onJade: '#1A2230',
    jade: '#199D78',
    jadeDeep: '#0E7357',
    jadeInk: '#0B6B50',
    coral: '#E88253',
    coralInk: '#A8440F',
    mist: '#99A6B8',
    textMuted: '#4F5B6E',
    neuDark: '#CED5DF',
    neuLight: '#FFFFFF',
    white: '#FFFFFF',
    controlOff: '#6B778A',
    trough: '#E4E8F0',
    focus: '#1D4ED8',
    dangerSolid: '#B23A2E',
    dangerPressed: '#8F2A1F',
    success: { soft: '#DDF3EA', ink: '#0B6B50' },
    warning: { soft: '#FBEBD3', ink: '#7A4A06' },
    danger: { soft: '#FBE4E0', ink: '#8F2A1F' },
    tier: {
      A: { soft: '#D3F0E4', ink: '#0B5A43' },
      B: { soft: '#E4F0CC', ink: '#3F5A12' },
      C: { soft: '#FBEBD3', ink: '#7A4A06' },
      D: { soft: '#FADCC8', ink: '#8A3608' },
      E: { soft: '#FBD9D3', ink: '#8F2A1F' },
      fallback: { soft: '#DDE2EA', ink: '#1A2230' },
    },
  },
  radii: { card: 26, cardSm: 18, chip: 12, pill: 999 },
  space: { xs: 4, sm: 8, md: 12, lg: 16, xl: 24, xxl: 32 },
  minTouch: 44,
  minSwitchRow: 48,
  fontFamily: { body: undefined as string | undefined, display: undefined as string | undefined },
  type: {
    eyebrow: { fontSize: 13, lineHeight: 18, fontWeight: '500' as const },
    title: { fontSize: 26, lineHeight: 32, fontWeight: '800' as const },
    display: { fontSize: 48, lineHeight: 52, fontWeight: '700' as const },
    body: { fontSize: 16, lineHeight: 22, fontWeight: '400' as const },
    bodyStrong: { fontSize: 16, lineHeight: 22, fontWeight: '600' as const },
    caption: { fontSize: 14, lineHeight: 20, fontWeight: '400' as const },
    chip: { fontSize: 12, lineHeight: 16, fontWeight: '700' as const },
  },
};

export const switchColors = {
  on: theme.colors.jadeDeep,
  off: theme.colors.controlOff,
  thumb: theme.colors.white,
};
