"""column comments

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-03 20:01:59.597689

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "events",
        "type",
        existing_type=sa.VARCHAR(),
        comment="harsh_brake, harsh_accel, sharp_corner, speeding",
        existing_nullable=False,
    )
    op.alter_column(
        "events",
        "peak_g",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment="Peak acceleration in g; null for speeding",
        existing_nullable=True,
    )
    op.alter_column(
        "incidents",
        "type",
        existing_type=sa.VARCHAR(),
        comment="Incident kind; crash",
        existing_nullable=False,
    )
    op.alter_column(
        "incidents",
        "peak_g",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment="Peak acceleration in g",
        existing_nullable=True,
    )
    op.alter_column(
        "incidents",
        "confirmed",
        existing_type=sa.VARCHAR(),
        comment="Driver answer: ok, help_needed, no_response; null if none",
        existing_nullable=True,
    )
    op.alter_column(
        "incidents",
        "sensor_snapshot",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        comment="JSON with peak_g, imu_samples, duration_ms around the crash",
        existing_nullable=True,
    )
    op.alter_column(
        "trip_chunks",
        "file_path",
        existing_type=sa.VARCHAR(),
        comment="Gzipped JSON chunk file under DATA_DIR",
        existing_nullable=False,
    )
    op.alter_column(
        "trip_features",
        "features",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        comment="TripFeatures JSON (app/features.py)",
        existing_nullable=False,
    )
    op.alter_column(
        "trip_scores",
        "confidence",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment="Model output 0 to 1, higher = riskier; score = 100 * (1 - confidence)",
        existing_nullable=False,
    )
    op.alter_column(
        "trip_scores",
        "score",
        existing_type=sa.INTEGER(),
        comment="Trip score 0 to 100, higher is safer",
        existing_nullable=False,
    )
    op.alter_column(
        "trip_scores",
        "tier",
        existing_type=sa.VARCHAR(),
        comment="Risk tier A to E from score (A >= 90, B >= 75, C >= 60, D >= 40)",
        existing_nullable=False,
    )
    op.alter_column(
        "trip_scores",
        "model_version",
        existing_type=sa.VARCHAR(),
        comment="Version of the model that produced the score",
        existing_nullable=False,
    )
    op.alter_column(
        "trips",
        "status",
        existing_type=sa.VARCHAR(),
        comment="uploading, processing, done, failed (see docs/data-model.md)",
        existing_nullable=False,
    )
    op.alter_column(
        "trips",
        "trip_type",
        existing_type=sa.VARCHAR(),
        comment="driver, passenger, transit, unknown; null until classified",
        existing_nullable=True,
    )
    op.alter_column(
        "trips",
        "label_source",
        existing_type=sa.VARCHAR(),
        comment="Who decided trip_type: bluetooth, rules, user; null if unlabelled",
        existing_nullable=True,
    )
    op.alter_column(
        "trips",
        "driver_likelihood",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment="Classifier probability 0 to 1 that the user was driving",
        existing_nullable=True,
    )
    op.alter_column(
        "trips",
        "transit_line",
        existing_type=sa.VARCHAR(),
        comment="Matched transit line name for transit trips",
        existing_nullable=True,
    )
    op.alter_column(
        "trips",
        "bluetooth_connected_ratio",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment="Share 0 to 1 of the trip the phone was on car Bluetooth",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "trips",
        "bluetooth_connected_ratio",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment=None,
        existing_comment="Share 0 to 1 of the trip the phone was on car Bluetooth",
        existing_nullable=True,
    )
    op.alter_column(
        "trips",
        "transit_line",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="Matched transit line name for transit trips",
        existing_nullable=True,
    )
    op.alter_column(
        "trips",
        "driver_likelihood",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment=None,
        existing_comment="Classifier probability 0 to 1 that the user was driving",
        existing_nullable=True,
    )
    op.alter_column(
        "trips",
        "label_source",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="Who decided trip_type: bluetooth, rules, user; null if unlabelled",
        existing_nullable=True,
    )
    op.alter_column(
        "trips",
        "trip_type",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="driver, passenger, transit, unknown; null until classified",
        existing_nullable=True,
    )
    op.alter_column(
        "trips",
        "status",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="uploading, processing, done, failed (see docs/data-model.md)",
        existing_nullable=False,
    )
    op.alter_column(
        "trip_scores",
        "model_version",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="Version of the model that produced the score",
        existing_nullable=False,
    )
    op.alter_column(
        "trip_scores",
        "tier",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="Risk tier A to E from score (A >= 90, B >= 75, C >= 60, D >= 40)",
        existing_nullable=False,
    )
    op.alter_column(
        "trip_scores",
        "score",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Trip score 0 to 100, higher is safer",
        existing_nullable=False,
    )
    op.alter_column(
        "trip_scores",
        "confidence",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment=None,
        existing_comment="Model output 0 to 1, higher = riskier; score = 100 * (1 - confidence)",
        existing_nullable=False,
    )
    op.alter_column(
        "trip_features",
        "features",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        comment=None,
        existing_comment="TripFeatures JSON (app/features.py)",
        existing_nullable=False,
    )
    op.alter_column(
        "trip_chunks",
        "file_path",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="Gzipped JSON chunk file under DATA_DIR",
        existing_nullable=False,
    )
    op.alter_column(
        "incidents",
        "sensor_snapshot",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        comment=None,
        existing_comment="JSON with peak_g, imu_samples, duration_ms around the crash",
        existing_nullable=True,
    )
    op.alter_column(
        "incidents",
        "confirmed",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="Driver answer: ok, help_needed, no_response; null if none",
        existing_nullable=True,
    )
    op.alter_column(
        "incidents",
        "peak_g",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment=None,
        existing_comment="Peak acceleration in g",
        existing_nullable=True,
    )
    op.alter_column(
        "incidents",
        "type",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="Incident kind; crash",
        existing_nullable=False,
    )
    op.alter_column(
        "events",
        "peak_g",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment=None,
        existing_comment="Peak acceleration in g; null for speeding",
        existing_nullable=True,
    )
    op.alter_column(
        "events",
        "type",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="harsh_brake, harsh_accel, sharp_corner, speeding",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
